import 'package:rubiks_core/src/model/cube.dart';

import '../../model/position.dart';

class AlgorithmSet {
  List<CornerPosition> corners;
  List<EdgePosition> edges;
  List<Turns> algos;
  List<Turns> premoves;

  AlgorithmSet(
      this.corners, this.edges, List<String> premoveString, List<String> algoStrings)
      : algos = algoStrings.map((e) => Turns.fromString(e)).toList(), premoves = premoveString.map((e) => Turns.fromString(e)).toList();
}

AlgorithmSet CMLL = AlgorithmSet([CornerPosition.LUF, CornerPosition.LUB, CornerPosition.RUF, CornerPosition.RUB], [], ["u", "u2", "u'", ""], [
"", // always add empty algo for skipping this step
"RUR'F'RUR'U'R'FR2U'R'",
"RM'UR'F'RUR'U'R'FR2U'R'M",
"RUR'U'R'FR2U'R'U'RUR'F'",
"RM'UR'U'R'MFR2U'R'U'RUR'F'",
"RM'U'LU2R'URU2R'ML'",
"FRU'R'U'RUR'F'RUR'U'R'FRF'",
"RM'2DR'MURM'D'R2U'F'U'F",
"R'MU'R'MD'RM'U'R'MDRM'UR'MD'RM'UR'MDRM'2",
"FRU'R'U'RUR'F'RM'UR'U'R'MFRF'",
"FR'FR2U'R'U'RUR'F'RUR'U'F'",
"RU2R'U'RUR'U'RU'R'",
"RM'U2R'U'RUR'U'RU'R'M",
"RUR'URU'R'URU2R'",
"RM'U'RM'U'RM'URM'URM'URM'",
"FRUR'U'RUR'U'RUR'U'F'",
"R'FRU2R'F'RUFRUR'UF'",
"FRU'R'URU2R'U'RUR'U'F'",
"RU2R2FRF'U2R'FRF'",
"RUR'URUR'MFR'F'RM'",
"RM'U'RM'2D'RM'U'R'MDRM'2UR'M",
"RM'U'R'MFU2RM'2FRM'U'RM'",
"RU2R2U'R2U'R2'U2R",
"FRUR'U'RUR'U'F'",
"FSRUR'U'RUR'U'FS'",
"FURU'R'URU'R'F'",
"F'L'U'LUL'U'LUF",
"R'MURM'2U'RM'2'U'RM'2UR'M",
"RM'U'RM'2URM'2URM'2U'RM'",
"R'U2RM'U'RM'U2RM'URM'U2R",
"FURU'R'URU'R2'F'RURU'R'",
"FR'F'RU2RU'R'URU2R'",
"RU2R'U'RU'R2ULU'RUL'",
"R'F2DR2U'R2D'F2R",
"R'FRUFU'RUR'U'F'",
"RUR'U'R'FR2UR'U'RUR'U'F'",
"RU2R'U'RUR'U2R'FRF'",
"R'U2RUR'UR2U'L'UR'U'L",
"RM'FRF'RM'U'R'U'RU'R'",
"RM'U'RM'2D'RM'UR'MDRM'2UR'M",
"R'URU'R2FR2UR'U'F'R",
"R'ULU'RU'L'U'LU'L'",
"RU2R'U'F'RU2R'U'RU'R'FRU'R'",
"R'U'R'FRF'RU'R'U2R",
"R'U'RU'R'UF'UFR",
"R2DR'U2RD'R'U2R'",
"RM'U'R'MU'RM'U'R'MU'F'U2F",
"R2D'RU2R'DRU2R",
"R'FRUR'FRUFU2F'",
"RU2R2U'R2U'R'UR'U'RUR'UR",
"R2FU'FUF2R2U'R'FR",
"R'U'RU'R'U2'R2UR'URU2'R'",
"R'FRU'R'U'RUR'F'RUR'U'R'FRF'R",
"FR2DR'URD'R2U'F'",
"RUR'U'R'F2R2U'R'U'RUR'F2",
"RM'U'R'MUR'MD'RM'U'R'MDRM'",
"R'FU'RFR'URF'",
"R'DRU'RU'R'UR'D'R",
"RM'URM'D'RM'URM'DRM'U'RM'",
"RU'R'U'RURDR'URD'R2",
"FRUR'U'F'",
"FSRUR'U'F'S'",
"FURU'R'F'",
"RM'UR'U'R'MFRF'",
"RUR'U'R'FRF'",
"L'M'U'LULMF'L'F",
"L'U'LULF'L'F",
"FRU'R'URUR'F'",
"'RUR'URU'R'UR'U'R2U'R2U2R",
"FR'FR2U'R'U'RUR'F2",
"RU2'R'U'RU'R2'U2'RUR'UR",
"R'URM'U2'R2'FRF'RM'",
"R'MURM'U2'R2'FRF'R",
"FRUR'U'RU'R'U'RUR'F'",
"R'MD'RM'UR'MDRM'U'RM'UR'M",
"R'DRU'RUR'UR'D'R",
"RM'U'RM'DRM'URM'D'RM'URM'",
"R'UR2DR'MU2RM'D'R2'U'R",
"RM'2'D'RM'UR'MDRM'2U'R'MU'RM'",
"RM'U'RM'2D'RM'U2R'MDRM'2UR'M",
"RUR'URU2R'",
"RM'UR'URU2R'M",
"L'U2LU2'LMF'L'FM'",
"L'U2LU2'LF'L'F",
"MFR'F'RU2RU2'R'M",
"FR'F'RU2RU2'R'",
"RUR'U'R'FRF'RUR'URU2'R'",
"RUR'URU'RDR'U'RD'R2'",
"RUR'UL'URU'LU2R'",
"RUR'UR'FRF'RU2'R'",
"RU'L'UR'U'L",
"RM'U'RM'FR'F'R",
"LU'R'UL'U'R",
"R'U'RU'R'U2'R",
"R'MU'RU'R'U2'RM'",
"RU2R'U'RU'R'",
"R2DR'URD'R'UR'U'RU'R'",
"RM'RDR'URD'R'UR'U'RU'R'M",
"MF'LFL'U2'L'U2LM'",
"F'LFL'U2'L'U2L",
"RU2'R'U2R'MFRF'M'",
"RU2'R'U2R'FRF'",
"L'URU'LUR'",
"R'FRF'RM'UR'M",
"R'ULU'RUL'",
"R'U'RU'LU'R'UL'U2R",
"R'U'RU'R'UR'FRF'UR",
"R2D'RU'R'DRUR",
"FRU'R'U'RUR'F'",
"F'RM'URM'U'RM'FRM'",
"F'RM'UR'U'RM'FR",
"FR'F'RM'URU'R'M",
"FR'F'RURU'R'",
"RU2R'U'RUR'U'RUR'U'RU'R'",
"RUR'U'R'FRF'R'FRF'RM'UR'M",
"RUR'URU'R'URU'R'URU2R'",
"RU2RDR'U2RD'R2'",
"RUR'UR'FRF'U2R'FRF'",
"RUR'U'F'U2'FURUR'",
"R'U'RUR'F'RUR'U'R'FR2",
"RU2'R2'FRF'RU2'R'",
"RM'U2'R2'FRF'RU2'RM'",
"R'U2R'D'RU2R'DR2",
"RUR'U'R'FR2U'R'URUR'F'",
]);
